### ISSUE TITLE
spurious 'WARNING: Use of undeclared Var'

### ISSUE THREAD

**Issue by frankhale** [tomjakubowski/weasel#66] opened 2015-09-18 21:39 UTC
Each time I try to reference a var in my namespace I see a warning telling me that I am trying to use an undeclared var. Here is a sample that in fact does work even though I get the warning:

Is this a bug in Weasel? I'm using the Chestnut lein template.

```
myapp.server=> (browser-repl)
<< started Weasel server on ws://0.0.0.0:9001 >>
<< waiting for client to connect ...  connected! >>
To quit, type: :cljs/quit
nil
cljs.user=> (in-ns 'myapp.core)
nil
myapp.core=> app-state
WARNING: Use of undeclared Var myapp.core/app-state at line 1 <cljs repl>
#object [cljs.core.Atom {:val {:text "Hello Chestnut!"}}]
myapp.core=>
```

**Comment by tomjakubowski** [comment] 2015-09-28 05:57
I know I've seen things like this in the past! Unfortunately I'm not able to put much time into maintaining my OSS projects these days, but if you or someone else can investigate the cause and fix it I'm always accepting patches!

**Comment by hookercookerman** [comment] 2015-10-16 15:21
I am currently also experiencing this problem; nothing special about mysetup just latest clojurescript

**Comment by futuro** [comment] 2015-11-16 22:28
I'm not certain if this is weasel specific, as I've encountered this problem with just figwheel, as well as figwheel+piggieback.

After digging around a little, I think this might be caused by figwheel, and is fixed in figwheel v0.5.0-1, but I'm not 100% certain at this point. I'll update once I know more.

**Comment by futuro** [comment] 2015-11-16 22:36
Updating from figwheel v0.4.0 to v0.5.0-1 seems to have fixed the issue.

**Comment by tomjakubowski** [comment] 2015-11-16 23:41
Thanks for looking into it, @futuro. @hookercookerman and @frankhale does upgrading figwheel resolve the issue for you, too?

**Closed** 2015-11-17 13:31 UTC

**Comment by frankhale** [comment] 2015-11-17 13:33
Looks like you guys squared it away but I cannot test this right now because it seems upgrading figwheel in the chestnut template fails for me.
