### ISSUE TITLE
Problem with multiple source paths

### ISSUE THREAD

**Issue by lgrapenthin** [tomjakubowski/weasel#41] opened 2015-01-20 10:35 UTC
I am not sure if this is a problem with piggieback or weasel and would need some time to narrow it down if this is necessary:

I have a cljs.user namespace in my /src/dev/cljs/cljs/user.cljs. "src/dev/cljs" is part of the cljsbuild source vector if I am in the dev profile.

I also have a myproject.core namespace in /src/cljs/myproject/core.cljs. "src/cljs/" is obviosuly also part of the cljsbuild source vector.

When I start the weasel REPL, it complains that it can't find myproject.core. This is happening with weasel 0.5.0, clojurescript 2665 and cljsbuild-0.1.5-SNAPSHOT. With Clojurescript 2511, piggieback 0.1.3 and weasel 0.4.2 I don't have the problem.

**Comment by mfikes** [comment] 2015-01-20 12:09
Perhaps this is a duplicate of #28

**Comment by lgrapenthin** [comment] 2015-01-20 12:47
Seems very likely. But the error directly refers to the ns form instead of specific vars.

**Comment by mfikes** [comment] 2015-01-20 14:08
@lgrapenthin Right. Currently you get `ExceptionInfo No such namespace` errors with the latest ClojureScript releases, but previously the same root cause would result in `WARNING: Referred var xxx.yyy/zzz does not exist` warnings.

I created a reduction in the form of a minimal repository capable of reproducing it: https://github.com/mfikes/weasel-src-paths

**Comment by lgrapenthin** [comment] 2015-01-20 14:38
Unless this is slurped somewhere, I currently don't get the WARNING (versions specified above).

**Comment by jaen** [comment] 2015-02-10 10:33
Also hit me when https://github.com/tomjakubowski/weasel/pull/44 fixed another issue I was having.
The `:source-paths` workaround doesn't seem to work for me though.

**Comment by the-kenny** [comment] 2015-02-10 10:58
For the record: In order to be able to require your own project's CLJS-Namespaces, you have to add the source-directories to leiningens ```:source-paths```.

**Comment by tomjakubowski** [comment] 2015-02-10 12:31
Closing as a duplicate of #28. Feel free to ping this issue if a subsequent fix for #28 doesn't fix your issue!

**Closed by tomjakubowski** 2015-02-10 12:31 UTC
